# Generated by Django 3.1.2 on 2020-10-10 22:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielens_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('date_rated', models.DateTimeField(default=datetime.datetime(2020, 10, 10, 22, 25, 30, 354279, tzinfo=utc))),
                ('who_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
