# Generated by Django 3.1.2 on 2020-10-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movielens_id',
            field=models.IntegerField(),
        ),
    ]
