# Generated by Django 3.1.2 on 2020-10-11 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20201011_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 21, 36, 40, 717214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movielens_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
