# Generated by Django 3.1.2 on 2020-10-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20201025_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movielens_user_id',
        ),
    ]
