# Generated by Django 3.1.2 on 2020-10-11 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20201011_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 21, 37, 41, 3367, tzinfo=utc)),
        ),
    ]
