# Generated by Django 3.1.2 on 2020-10-11 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20201011_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 21, 38, 43, 423106, tzinfo=utc)),
        ),
    ]
