# Generated by Django 3.1.2 on 2020-11-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20201102_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictedRating',
        ),
    ]
