# Generated by Django 3.1.2 on 2020-10-13 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20201011_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 14, 18, 20, 286024, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('movielens_id', 'who_rated'), name='One ratings has to be given to a film by a user'),
        ),
    ]
