# Generated by Django 3.1.2 on 2020-11-02 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0006_delete_predictedrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_value', models.FloatField()),
                ('date_rated', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='predictedrating',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='No multiple predicted ratings'),
        ),
    ]
