# Generated by Django 3.1.2 on 2020-10-14 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20201013_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='One ratings has to be given to a film by a user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 19, 38, 13, 740575, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('movielens_id', 'who_rated'), name='No multiple ratings'),
        ),
    ]
