# Generated by Django 3.1.2 on 2020-10-14 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20201014_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 20, 34, 38, 397407, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.genre')),
                ('movielens_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie')),
            ],
        ),
    ]
