# Generated by Django 3.1.2 on 2020-10-15 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_auto_20201014_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviegenre',
            old_name='movielens_id',
            new_name='movie_id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 0, 27, 17, 777103, tzinfo=utc)),
        ),
    ]
