# Generated by Django 3.1.2 on 2020-11-02 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0009_predictedrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='predictedrating',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='No multiple predicted ratings'),
        ),
    ]
