# Generated by Django 3.1.2 on 2020-11-02 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0010_auto_20201102_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictedRating',
            new_name='TopHundredMovies',
        ),
        migrations.RenameField(
            model_name='tophundredmovies',
            old_name='date_rated',
            new_name='date_predicted',
        ),
    ]
