# Generated by Django 3.1.2 on 2020-11-02 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0011_auto_20201102_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopHundredMovies',
            new_name='TopMovie',
        ),
    ]
