# Generated by Django 3.1.3 on 2021-02-23 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_auto_20201102_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(verbose_name='IMdB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movielens_id',
            field=models.IntegerField(verbose_name='movielens ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(verbose_name='tMdB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_released',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating'),
        ),
    ]
