# Generated by Django 3.1.3 on 2021-02-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0013_auto_20210224_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(verbose_name='iMdB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_released',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
