# Generated by Django 3.1.2 on 2020-10-16 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0030_jakastam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movielens_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
