# Generated by Django 3.1.2 on 2020-10-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0031_auto_20201017_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movielens_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie', to_field='movielens_id'),
        ),
    ]
