# Generated by Django 3.1.2 on 2020-10-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0032_auto_20201017_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JakasTam',
        ),
    ]
