# Generated by Django 3.1.2 on 2020-10-20 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0033_delete_jakastam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movieactor',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie_id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='MovieActor',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
