# Generated by Django 3.1.2 on 2020-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0034_auto_20201020_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('movies', models.ManyToManyField(to='recommender.Movie')),
            ],
        ),
    ]
