# Generated by Django 3.1.2 on 2020-10-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0037_auto_20201021_1835'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='No multiple ratings',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movielens_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='recommender.movie'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('movie', 'who_rated'), name='No multiple ratings'),
        ),
    ]
